#!/usr/bin/python3

from sys import argv
from datetime import date

licenses = {
    "MIT": """MIT License

Copyright (c) {year} {name}

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE."""
}

if len(argv) < 2:
    print(f"usage: {argv[0]} <license type> <full name>")
    exit(1)

license_type = argv[1].upper()
full_name = argv[2]
current_year = date.today().year

license_content = ""
match license_type:
    case "MIT":
        license_content = licenses[license_type].format(year=current_year, name=full_name)
    case _:
        print(f"The {license_type} license is not supported yet.")
        exit(1)

license_file = open("LICENSE", "w")
license_file.write(license_content)

